[package]
name = "consilium-desktop"
version = "0.1.0"
description = "Nativa Tauri de CONSILIUM Desktop"
edition = "2021"

[lib]
name = "consilium_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
consilium-tauri-native = { path = "../../../rust/tauri-native" }